-- =============================================================================
-- Zenith Harvest — Script DDL PostgreSQL
-- =============================================================================
-- 39 tabelas. Tipos adaptados aos nativos ideais do PostgreSQL.
-- Compatível com PostgreSQL 13+ (gen_random_uuid no core; pgcrypto p/ versões antigas).
--
-- CONVENÇÕES:
--   - Nomes em PascalCase entre aspas duplas (fiel ao modelo).
--     ATENÇÃO: "User" é palavra reservada no PostgreSQL — por isso TODA query
--     precisará das aspas. Se preferir, renomeie para "AppUser"/"Users".
--   - PK de entidade: UUID DEFAULT gen_random_uuid()
--   - PK de lookup:   INTEGER GENERATED BY DEFAULT AS IDENTITY
--   - "Code":         INTEGER GENERATED BY DEFAULT AS IDENTITY (sequência por tabela, 1 em 1)
--   - Dinheiro: NUMERIC(15,2) | NDVI: NUMERIC(4,3) | %: NUMERIC(5,2)
--   - Timestamps: TIMESTAMPTZ | Boolean nativo | JSON: JSONB
--   - NOT NULL conservador: só o que existe na criação. Operacionais = nullable.
--   - FKs adicionadas no final (evita problema de ordem de criação).
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid() em versões < 13

-- =============================================================================
-- SEÇÃO 0 — LIMPEZA (idempotente)
-- =============================================================================
DROP TABLE IF EXISTS
  "AuditLog",
  "Payment", "PaymentInvoice", "PaymentType", "PaymentSituation",
  "PreventiveAlert", "SatelliteAnalysis", "ClaimItem", "Claim", "PolicyItem", "Policy",
  "PolicySituation", "ClaimSituation", "ClaimEventType", "ClaimCategory", "ClaimSubCategory",
  "SatelliteSource", "SatelliteClass", "AlertType", "AlertSeverity", "AlertSituation", "RejectionReason",
  "InsuranceQuote", "Insurance", "Insurer",
  "InsuranceQuoteSituation", "InsurerSituation", "InsuranceSituation",
  "Plot", "Farm", "Crop", "Biome", "ProductionSystem", "PlotSituation",
  "AccessLog", "Credential", "Address", "User", "AccessLogAction"
CASCADE;


-- =============================================================================
-- SEÇÃO 1 — USERS DOMAIN
-- =============================================================================

CREATE TABLE "AccessLogAction" (
  "Id"          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(200)  NOT NULL,
  "Active"      BOOLEAN       NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "Address" (
  "Id"         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "Street"     VARCHAR(150) NOT NULL,
  "Number"     INTEGER      NOT NULL,
  "Neighboor"  VARCHAR(100) NOT NULL,
  "City"       VARCHAR(100) NOT NULL,
  "Complement" VARCHAR(150),
  "PostalCode" VARCHAR(9)   NOT NULL,
  "UF"         CHAR(2)      NOT NULL,
  "Country"    VARCHAR(60)  NOT NULL
);

CREATE TABLE "User" (
  "Id"          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "Cpf"         VARCHAR(18)  NOT NULL UNIQUE,
  "Name"        VARCHAR(150) NOT NULL,
  "LastName"    VARCHAR(150) NOT NULL,
  "AddressId"   UUID,
  "Email"       VARCHAR(150) NOT NULL UNIQUE,
  "Phone"       VARCHAR(20)  NOT NULL,
  "Code"        INTEGER      GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "LastLoginAt" TIMESTAMPTZ,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"    TIMESTAMPTZ,
  "UpdatedAt"   TIMESTAMPTZ,
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "Credential" (
  "Id"        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "UserId"    UUID         NOT NULL,
  "Password"  VARCHAR(255) NOT NULL,
  "Secret"    VARCHAR(255) NOT NULL,
  "CreatedAt" TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"  TIMESTAMPTZ,
  "DeletedAt" TIMESTAMPTZ
);

CREATE TABLE "AccessLog" (
  "Id"                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "UserId"            UUID,
  "AccessLogActionId" INTEGER      NOT NULL,
  "Ip"                VARCHAR(45),
  "UserAgent"         VARCHAR(500),
  "Success"           BOOLEAN      NOT NULL,
  "FailureReason"     VARCHAR(200),
  "CreatedAt"         TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- =============================================================================
-- SEÇÃO 2 — FARM DOMAIN
-- =============================================================================

CREATE TABLE "Biome" (
  "Id"                 INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description"        VARCHAR(100) NOT NULL,
  "RegionalRiskFactor" NUMERIC(4,2) NOT NULL DEFAULT 1.0,
  "Active"             BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"           TIMESTAMPTZ,
  "DeletedAt"          TIMESTAMPTZ
);

CREATE TABLE "ProductionSystem" (
  "Id"              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description"     VARCHAR(100) NOT NULL,
  "PremiumDiscount" NUMERIC(5,2) NOT NULL DEFAULT 0,
  "Active"          BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"        TIMESTAMPTZ,
  "DeletedAt"       TIMESTAMPTZ
);

CREATE TABLE "PlotSituation" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "IsTerminal"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"    TIMESTAMPTZ,
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "Crop" (
  "Id"                     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "Name"                   VARCHAR(80)  NOT NULL,
  "ScientificName"         VARCHAR(120) NOT NULL,
  "Code"                   INTEGER      GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "AverageCycleDays"       INTEGER,
  "ExpectedNdviMin"        NUMERIC(4,3),
  "ExpectedNdviMax"        NUMERIC(4,3),
  "AverageValuePerHectare" NUMERIC(15,2),
  "DroughtVulnerability"   NUMERIC(3,1),
  "FrostVulnerability"     NUMERIC(3,1),
  "Status"                 BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"              TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"               TIMESTAMPTZ,
  "DeletedAt"              TIMESTAMPTZ,
  CONSTRAINT "CkCropNdviRange" CHECK (
    ("ExpectedNdviMin" IS NULL OR "ExpectedNdviMin" BETWEEN -1 AND 1) AND
    ("ExpectedNdviMax" IS NULL OR "ExpectedNdviMax" BETWEEN -1 AND 1)
  )
);

CREATE TABLE "Farm" (
  "Id"                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "UserId"            UUID          NOT NULL,
  "Name"              VARCHAR(150)  NOT NULL,
  "Code"              INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "CarRegistration"   VARCHAR(50)   NOT NULL,
  "Nirf"              VARCHAR(20)   NOT NULL,
  "Latitude"          NUMERIC(10,7) NOT NULL,
  "Longitude"         NUMERIC(10,7) NOT NULL,
  "TotalAreaHectares" NUMERIC(10,2) NOT NULL,
  "State"             CHAR(2)       NOT NULL,
  "BiomeId"           INTEGER,
  "PropertyType"      VARCHAR(30),
  "PolygonWkt"        TEXT,
  "Active"            BOOLEAN       NOT NULL DEFAULT TRUE,
  "CreatedAt"         TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"          TIMESTAMPTZ,
  "DeletedAt"         TIMESTAMPTZ,
  CONSTRAINT "CkFarmGeo" CHECK (
    "Latitude" BETWEEN -90 AND 90 AND "Longitude" BETWEEN -180 AND 180
  )
);

CREATE TABLE "Plot" (
  "Id"                   UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "FarmId"               UUID          NOT NULL,
  "CropId"               UUID,
  "PlotSituationId"      INTEGER       NOT NULL,
  "ProductionSystemId"   INTEGER,
  "Code"                 INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "Identifier"           VARCHAR(40)   NOT NULL,
  "AreaHectares"         NUMERIC(10,2) NOT NULL,
  "PlantingDate"         DATE,
  "EstimatedHarvestDate" DATE,
  "CycleDays"            INTEGER,
  "SeedVariety"          VARCHAR(100),
  "PolygonWkt"           TEXT,
  "CreatedAt"            TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"             TIMESTAMPTZ,
  "DeletedAt"            TIMESTAMPTZ,
  CONSTRAINT "UqPlotFarmIdentifier" UNIQUE ("FarmId", "Identifier")
);


-- =============================================================================
-- SEÇÃO 3 — INSURANCE CATALOG DOMAIN
-- =============================================================================

CREATE TABLE "InsurerSituation" (
  "Id"                INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description"       VARCHAR(100) NOT NULL,
  "AllowsNewPolicies" BOOLEAN      NOT NULL DEFAULT TRUE,
  "Active"            BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"          TIMESTAMPTZ,
  "DeletedAt"         TIMESTAMPTZ
);

CREATE TABLE "InsuranceSituation" (
  "Id"              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description"     VARCHAR(100) NOT NULL,
  "AllowsNewQuotes" BOOLEAN      NOT NULL DEFAULT TRUE,
  "Active"          BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"        TIMESTAMPTZ,
  "DeletedAt"       TIMESTAMPTZ
);

CREATE TABLE "InsuranceQuoteSituation" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "IsTerminal"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "Insurer" (
  "Id"                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "CorporateName"      VARCHAR(200) NOT NULL,
  "TradeName"          VARCHAR(150),
  "Cnpj"               VARCHAR(18)  NOT NULL UNIQUE,
  "Code"               INTEGER      GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "SusepCode"          VARCHAR(20)  NOT NULL UNIQUE,
  "CommercialEmail"    VARCHAR(150),
  "Phone"              VARCHAR(20),
  "LogoUrl"            VARCHAR(500),
  "AdminFeePct"        NUMERIC(5,2) NOT NULL DEFAULT 5.0,
  "TakeRatePct"        NUMERIC(5,2) NOT NULL DEFAULT 8.0,
  "Active"             BOOLEAN      NOT NULL DEFAULT TRUE,
  "InsurerSituationId" INTEGER      NOT NULL,
  "AccreditedAt"       DATE         NOT NULL DEFAULT CURRENT_DATE,
  "CreatedAt"          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"           TIMESTAMPTZ,
  "DeletedAt"          TIMESTAMPTZ
);

CREATE TABLE "Insurance" (
  "Id"                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "InsurerId"             UUID         NOT NULL,
  "Name"                  VARCHAR(150) NOT NULL,
  "Description"           VARCHAR(500) NOT NULL,
  "Code"                  INTEGER      GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "DeductiblePct"         NUMERIC(5,2) NOT NULL DEFAULT 10.00,
  "GraceDays"             INTEGER      NOT NULL DEFAULT 7,
  "MaxCoveragePerHectare" NUMERIC(15,2),
  "BaseRatePct"           NUMERIC(5,3),
  "AvailableStates"       VARCHAR(100),
  "InsuranceSituationId"  INTEGER      NOT NULL,
  "Active"                BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"             TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"              TIMESTAMPTZ,
  "DeletedAt"             TIMESTAMPTZ,
  CONSTRAINT "UqInsuranceInsurerName" UNIQUE ("InsurerId", "Name")
);

CREATE TABLE "InsuranceQuote" (
  "Id"               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "UserId"           UUID          NOT NULL,
  "PlotId"           UUID          NOT NULL,
  "InsuranceId"      UUID          NOT NULL,
  "QuoteSituationId" INTEGER       NOT NULL,
  "Code"             INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "InsuredAmount"    NUMERIC(15,2),
  "TotalPremium"     NUMERIC(15,2),
  "MonthlyPremium"   NUMERIC(15,2),
  "RegionalFactor"   NUMERIC(5,3)  DEFAULT 1.000,
  "HistoryFactor"    NUMERIC(5,3)  DEFAULT 1.000,
  "ValidUntil"       TIMESTAMPTZ,
  "AcceptedAt"       TIMESTAMPTZ,
  "CreatedAt"        TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"         TIMESTAMPTZ,
  "DeletedAt"        TIMESTAMPTZ
);


-- =============================================================================
-- SEÇÃO 4 — OPERATION DOMAIN
-- =============================================================================

CREATE TABLE "PolicySituation" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "AllowsClaim" BOOLEAN      NOT NULL DEFAULT FALSE,
  "IsTerminal"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"    TIMESTAMPTZ,
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "ClaimSituation" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(150) NOT NULL,
  "AllowsClaim" BOOLEAN      NOT NULL DEFAULT FALSE,
  "IsTerminal"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "ClaimEventType" (
  "Id"            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description"   VARCHAR(150) NOT NULL,
  "RequiresPhoto" BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"        BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "DeletedAt"     TIMESTAMPTZ
);

CREATE TABLE "ClaimCategory" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(150) NOT NULL,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "ClaimSubCategory" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(150) NOT NULL,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "SatelliteSource" (
  "Id"                   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description"          VARCHAR(100) NOT NULL,
  "Operator"             VARCHAR(60),
  "Resolution"           VARCHAR(20),
  "RevisitFrequencyDays" INTEGER,
  "Active"               BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"            TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "DeletedAt"            TIMESTAMPTZ
);

CREATE TABLE "SatelliteClass" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "Severity"    INTEGER      NOT NULL DEFAULT 0,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "AlertType" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(150) NOT NULL,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "AlertSeverity" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "Level"       INTEGER      NOT NULL,
  "ColorHex"    VARCHAR(7),
  "PushNotify"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "SmsNotify"   BOOLEAN      NOT NULL DEFAULT FALSE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "AlertSituation" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "IsTerminal"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "RejectionReason" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(200) NOT NULL,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "EditedAt"    TIMESTAMPTZ,
  "DeletedAt"   TIMESTAMPTZ
);

CREATE TABLE "Policy" (
  "Id"                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "PolicyNumber"      VARCHAR(30)   NOT NULL UNIQUE,
  "InsuranceQuoteId"  UUID,
  "PlotId"            UUID          NOT NULL,
  "InsurerId"         UUID          NOT NULL,
  "InsuranceId"       UUID          NOT NULL,
  "PolicySituationId" INTEGER       NOT NULL,
  "Code"              INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "InsuredAmount"     NUMERIC(15,2) NOT NULL,
  "TotalPremium"      NUMERIC(15,2),
  "MonthlyPremium"    NUMERIC(15,2),
  "DeductiblePct"     NUMERIC(5,2),
  "MaxCoverage"       NUMERIC(15,2),
  "AccumulatedPaid"   NUMERIC(15,2) NOT NULL DEFAULT 0,
  "StartDate"         DATE          NOT NULL,
  "EndDate"           DATE          NOT NULL,
  "ContractedAt"      TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "CancelledAt"       TIMESTAMPTZ,
  "CreatedAt"         TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"          TIMESTAMPTZ,
  "DeletedAt"         TIMESTAMPTZ,
  CONSTRAINT "CkPolicyDates" CHECK ("EndDate" > "StartDate")
);

CREATE TABLE "PolicyItem" (
  "Id"                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "PolicyId"          UUID          NOT NULL,
  "ClaimEventTypeId"  INTEGER       NOT NULL,
  "CoveragePct"       NUMERIC(5,2)  NOT NULL DEFAULT 100,
  "MaxCoverageAmount" NUMERIC(15,2),
  "Notes"             VARCHAR(500),
  CONSTRAINT "UqPolicyItemEvent" UNIQUE ("PolicyId", "ClaimEventTypeId")
);

CREATE TABLE "Claim" (
  "Id"                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "ClaimNumber"         VARCHAR(30)   NOT NULL UNIQUE,
  "PolicyId"            UUID          NOT NULL,
  "ClaimSituationId"    INTEGER       NOT NULL,
  "CategoryId"          INTEGER       NOT NULL,
  "Code"                INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "SubCategoryId"       INTEGER       NOT NULL,
  "Description"         TEXT,
  "PhotoUrl"            VARCHAR(500),
  "OpeningGpsLat"       NUMERIC(10,7),
  "OpeningGpsLng"       NUMERIC(10,7),
  "NdviBefore"          NUMERIC(4,3),
  "NdviAfter"           NUMERIC(4,3),
  "TotalLossPct"        NUMERIC(5,2),
  "TotalAffectedAreaHa" NUMERIC(10,2),
  "CalculatedAmount"    NUMERIC(15,2),
  "ApprovedAmount"      NUMERIC(15,2),
  "MlConfidenceScore"   NUMERIC(5,2),
  "FraudFlag"           BOOLEAN       NOT NULL DEFAULT FALSE,
  "RejectionReasonId"   INTEGER,
  "AnalystId"           UUID,
  "ApprovedAt"          TIMESTAMPTZ,
  "CreatedAt"           TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"            TIMESTAMPTZ,
  "PaidAt"              TIMESTAMPTZ,
  "DeletedAt"           TIMESTAMPTZ
);

CREATE TABLE "ClaimItem" (
  "Id"               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "ClaimId"          UUID          NOT NULL,
  "ClaimEventTypeId" INTEGER       NOT NULL,
  "AffectedAreaHa"   NUMERIC(10,2),
  "LossPct"          NUMERIC(5,2),
  "NdviBefore"       NUMERIC(4,3),
  "NdviAfter"        NUMERIC(4,3),
  "ItemAmount"       NUMERIC(15,2),
  "Description"      VARCHAR(500)
);

CREATE TABLE "SatelliteAnalysis" (
  "Id"                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "ClaimId"           UUID,
  "PlotId"            UUID          NOT NULL,
  "SatelliteSourceId" INTEGER       NOT NULL,
  "SatelliteClassId"  INTEGER,
  "ImageDate"         DATE          NOT NULL,
  "SceneId"           VARCHAR(100),
  "ImageUrl"          VARCHAR(500),
  "MeanNdvi"          NUMERIC(4,3),
  "MeanEvi"           NUMERIC(4,3),
  "CloudCoveragePct"  NUMERIC(5,2),
  "AffectedAreaM2"    NUMERIC(15,2),
  "MlConfidence"      NUMERIC(5,2),
  "ProcessedAt"       TIMESTAMPTZ,
  "CreatedAt"         TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"          TIMESTAMPTZ,
  "DeletedAt"         TIMESTAMPTZ
);

CREATE TABLE "PreventiveAlert" (
  "Id"               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "PlotId"           UUID         NOT NULL,
  "AlertTypeId"      INTEGER      NOT NULL,
  "AlertSeverityId"  INTEGER      NOT NULL,
  "AlertSituationId" INTEGER      NOT NULL,
  "Message"          TEXT         NOT NULL,
  "ObservedNdvi"     NUMERIC(4,3),
  "ExpectedNdvi"     NUMERIC(4,3),
  "DropPct"          NUMERIC(5,2),
  "IssuedAt"         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  "ViewedAt"         TIMESTAMPTZ,
  "CreatedAt"        TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- =============================================================================
-- SEÇÃO 5 — FINANCIAL DOMAIN
-- =============================================================================

CREATE TABLE "PaymentType" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "Direction"   VARCHAR(3)   NOT NULL,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT "CkPaymentTypeDirection" CHECK ("Direction" IN ('IN','OUT'))
);

CREATE TABLE "PaymentSituation" (
  "Id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Description" VARCHAR(100) NOT NULL,
  "IsTerminal"  BOOLEAN      NOT NULL DEFAULT FALSE,
  "IsSuccess"   BOOLEAN      NOT NULL DEFAULT FALSE,
  "Active"      BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedAt"   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "PaymentInvoice" (
  "Id"            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "InvoiceNumber" VARCHAR(30)   NOT NULL UNIQUE,
  "UserId"        UUID          NOT NULL,
  "InsurerId"     UUID,
  "Code"          INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "TotalAmount"   NUMERIC(15,2),
  "DueDate"       DATE          NOT NULL,
  "IssuedAt"      TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "PaidAt"        TIMESTAMPTZ,
  "Active"        BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE "Payment" (
  "Id"                 UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "PaymentTypeId"      INTEGER       NOT NULL,
  "PaymentSituationId" INTEGER       NOT NULL,
  "ClaimId"            UUID,
  "PolicyId"           UUID,
  "PaymentInvoiceId"   UUID,
  "Code"               INTEGER       GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "Amount"             NUMERIC(15,2) NOT NULL,
  "PixKey"             VARCHAR(140),
  "SentAt"             TIMESTAMPTZ,
  "ConfirmedAt"        TIMESTAMPTZ,
  "PspTransactionId"   VARCHAR(100),
  "Attempts"           SMALLINT      NOT NULL DEFAULT 0,
  "FailureReason"      VARCHAR(500),
  "CreatedAt"          TIMESTAMPTZ   NOT NULL DEFAULT now(),
  "EditedAt"           TIMESTAMPTZ,
  "DeletedAt"          TIMESTAMPTZ,
  CONSTRAINT "CkPaymentClaimPolicyXor" CHECK (
    ("ClaimId" IS NOT NULL AND "PolicyId" IS NULL) OR
    ("ClaimId" IS NULL AND "PolicyId" IS NOT NULL)
  )
);


-- =============================================================================
-- SEÇÃO 6 — AUDIT
-- =============================================================================

CREATE TABLE "AuditLog" (
  "Id"              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "UserId"          UUID,
  "SystemActor"     VARCHAR(50),
  "Operation"       VARCHAR(30)  NOT NULL,
  "TargetEntity"    VARCHAR(50),
  "TargetEntityId"  VARCHAR(64),  -- polimórfico: guarda UUID de entidade ou Id de lookup
  "DescriptionJson" JSONB,        -- tipo ideal do Postgres p/ JSON (indexável)
  "Ip"              VARCHAR(45),
  "UserAgent"       VARCHAR(500),
  "RequestId"       UUID,
  "Success"         BOOLEAN      NOT NULL DEFAULT TRUE,
  "FailureReason"   VARCHAR(500),
  "OperatedAt"      TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- =============================================================================
-- SEÇÃO 7 — FOREIGN KEYS (adicionadas no fim p/ evitar ordem de criação)
-- =============================================================================

-- Users
ALTER TABLE "User"       ADD CONSTRAINT "FkUserAddress"     FOREIGN KEY ("AddressId") REFERENCES "Address"("Id");
ALTER TABLE "Credential" ADD CONSTRAINT "FkCredentialUser"  FOREIGN KEY ("UserId")    REFERENCES "User"("Id");
ALTER TABLE "AccessLog"  ADD CONSTRAINT "FkAccessLogUser"   FOREIGN KEY ("UserId")    REFERENCES "User"("Id") ON DELETE SET NULL;
ALTER TABLE "AccessLog"  ADD CONSTRAINT "FkAccessLogAction" FOREIGN KEY ("AccessLogActionId") REFERENCES "AccessLogAction"("Id");

-- Farm
ALTER TABLE "Farm" ADD CONSTRAINT "FkFarmUser"  FOREIGN KEY ("UserId")  REFERENCES "User"("Id");
ALTER TABLE "Farm" ADD CONSTRAINT "FkFarmBiome" FOREIGN KEY ("BiomeId") REFERENCES "Biome"("Id");
ALTER TABLE "Plot" ADD CONSTRAINT "FkPlotFarm"            FOREIGN KEY ("FarmId")             REFERENCES "Farm"("Id");
ALTER TABLE "Plot" ADD CONSTRAINT "FkPlotCrop"            FOREIGN KEY ("CropId")             REFERENCES "Crop"("Id");
ALTER TABLE "Plot" ADD CONSTRAINT "FkPlotSituation"       FOREIGN KEY ("PlotSituationId")    REFERENCES "PlotSituation"("Id");
ALTER TABLE "Plot" ADD CONSTRAINT "FkPlotProductionSystem"FOREIGN KEY ("ProductionSystemId") REFERENCES "ProductionSystem"("Id");

-- Insurance Catalog
ALTER TABLE "Insurer"        ADD CONSTRAINT "FkInsurerSituation"   FOREIGN KEY ("InsurerSituationId")   REFERENCES "InsurerSituation"("Id");
ALTER TABLE "Insurance"      ADD CONSTRAINT "FkInsuranceInsurer"   FOREIGN KEY ("InsurerId")            REFERENCES "Insurer"("Id");
ALTER TABLE "Insurance"      ADD CONSTRAINT "FkInsuranceSituation" FOREIGN KEY ("InsuranceSituationId") REFERENCES "InsuranceSituation"("Id");
ALTER TABLE "InsuranceQuote" ADD CONSTRAINT "FkQuoteUser"          FOREIGN KEY ("UserId")               REFERENCES "User"("Id");
ALTER TABLE "InsuranceQuote" ADD CONSTRAINT "FkQuotePlot"          FOREIGN KEY ("PlotId")               REFERENCES "Plot"("Id");
ALTER TABLE "InsuranceQuote" ADD CONSTRAINT "FkQuoteInsurance"     FOREIGN KEY ("InsuranceId")          REFERENCES "Insurance"("Id");
ALTER TABLE "InsuranceQuote" ADD CONSTRAINT "FkQuoteSituation"     FOREIGN KEY ("QuoteSituationId")     REFERENCES "InsuranceQuoteSituation"("Id");

-- Operation
ALTER TABLE "Policy" ADD CONSTRAINT "FkPolicyQuote"     FOREIGN KEY ("InsuranceQuoteId")  REFERENCES "InsuranceQuote"("Id");
ALTER TABLE "Policy" ADD CONSTRAINT "FkPolicyPlot"      FOREIGN KEY ("PlotId")            REFERENCES "Plot"("Id");
ALTER TABLE "Policy" ADD CONSTRAINT "FkPolicyInsurer"   FOREIGN KEY ("InsurerId")         REFERENCES "Insurer"("Id");
ALTER TABLE "Policy" ADD CONSTRAINT "FkPolicyInsurance" FOREIGN KEY ("InsuranceId")       REFERENCES "Insurance"("Id");
ALTER TABLE "Policy" ADD CONSTRAINT "FkPolicySituation" FOREIGN KEY ("PolicySituationId") REFERENCES "PolicySituation"("Id");

ALTER TABLE "PolicyItem" ADD CONSTRAINT "FkPolicyItemPolicy"    FOREIGN KEY ("PolicyId")         REFERENCES "Policy"("Id") ON DELETE CASCADE;
ALTER TABLE "PolicyItem" ADD CONSTRAINT "FkPolicyItemEventType" FOREIGN KEY ("ClaimEventTypeId") REFERENCES "ClaimEventType"("Id");

ALTER TABLE "Claim" ADD CONSTRAINT "FkClaimPolicy"          FOREIGN KEY ("PolicyId")          REFERENCES "Policy"("Id");
ALTER TABLE "Claim" ADD CONSTRAINT "FkClaimSituation"       FOREIGN KEY ("ClaimSituationId")  REFERENCES "ClaimSituation"("Id");
ALTER TABLE "Claim" ADD CONSTRAINT "FkClaimCategory"        FOREIGN KEY ("CategoryId")        REFERENCES "ClaimCategory"("Id");
ALTER TABLE "Claim" ADD CONSTRAINT "FkClaimSubCategory"     FOREIGN KEY ("SubCategoryId")     REFERENCES "ClaimSubCategory"("Id");
ALTER TABLE "Claim" ADD CONSTRAINT "FkClaimRejectionReason" FOREIGN KEY ("RejectionReasonId") REFERENCES "RejectionReason"("Id");

ALTER TABLE "ClaimItem" ADD CONSTRAINT "FkClaimItemClaim"     FOREIGN KEY ("ClaimId")          REFERENCES "Claim"("Id") ON DELETE CASCADE;
ALTER TABLE "ClaimItem" ADD CONSTRAINT "FkClaimItemEventType" FOREIGN KEY ("ClaimEventTypeId") REFERENCES "ClaimEventType"("Id");

ALTER TABLE "SatelliteAnalysis" ADD CONSTRAINT "FkSatAnalysisClaim"  FOREIGN KEY ("ClaimId")           REFERENCES "Claim"("Id");
ALTER TABLE "SatelliteAnalysis" ADD CONSTRAINT "FkSatAnalysisPlot"   FOREIGN KEY ("PlotId")            REFERENCES "Plot"("Id");
ALTER TABLE "SatelliteAnalysis" ADD CONSTRAINT "FkSatAnalysisSource" FOREIGN KEY ("SatelliteSourceId") REFERENCES "SatelliteSource"("Id");
ALTER TABLE "SatelliteAnalysis" ADD CONSTRAINT "FkSatAnalysisClass"  FOREIGN KEY ("SatelliteClassId")  REFERENCES "SatelliteClass"("Id");

ALTER TABLE "PreventiveAlert" ADD CONSTRAINT "FkAlertPlot"      FOREIGN KEY ("PlotId")           REFERENCES "Plot"("Id");
ALTER TABLE "PreventiveAlert" ADD CONSTRAINT "FkAlertType"      FOREIGN KEY ("AlertTypeId")      REFERENCES "AlertType"("Id");
ALTER TABLE "PreventiveAlert" ADD CONSTRAINT "FkAlertSeverity"  FOREIGN KEY ("AlertSeverityId")  REFERENCES "AlertSeverity"("Id");
ALTER TABLE "PreventiveAlert" ADD CONSTRAINT "FkAlertSituation" FOREIGN KEY ("AlertSituationId") REFERENCES "AlertSituation"("Id");

-- Financial
ALTER TABLE "PaymentInvoice" ADD CONSTRAINT "FkInvoiceUser"    FOREIGN KEY ("UserId")    REFERENCES "User"("Id");
ALTER TABLE "PaymentInvoice" ADD CONSTRAINT "FkInvoiceInsurer" FOREIGN KEY ("InsurerId") REFERENCES "Insurer"("Id");

ALTER TABLE "Payment" ADD CONSTRAINT "FkPaymentType"      FOREIGN KEY ("PaymentTypeId")      REFERENCES "PaymentType"("Id");
ALTER TABLE "Payment" ADD CONSTRAINT "FkPaymentSituation" FOREIGN KEY ("PaymentSituationId") REFERENCES "PaymentSituation"("Id");
ALTER TABLE "Payment" ADD CONSTRAINT "FkPaymentClaim"     FOREIGN KEY ("ClaimId")            REFERENCES "Claim"("Id");
ALTER TABLE "Payment" ADD CONSTRAINT "FkPaymentPolicy"    FOREIGN KEY ("PolicyId")           REFERENCES "Policy"("Id");
ALTER TABLE "Payment" ADD CONSTRAINT "FkPaymentInvoice"   FOREIGN KEY ("PaymentInvoiceId")   REFERENCES "PaymentInvoice"("Id");

-- Audit
ALTER TABLE "AuditLog" ADD CONSTRAINT "FkAuditLogUser" FOREIGN KEY ("UserId") REFERENCES "User"("Id") ON DELETE SET NULL;


-- =============================================================================
-- SEÇÃO 8 — ÍNDICES (FKs e colunas de busca frequente)
-- =============================================================================
CREATE INDEX "IxCredentialUser"     ON "Credential"("UserId");
CREATE INDEX "IxAccessLogUser"      ON "AccessLog"("UserId", "CreatedAt" DESC);
CREATE INDEX "IxFarmUser"           ON "Farm"("UserId");
CREATE INDEX "IxPlotFarm"           ON "Plot"("FarmId");
CREATE INDEX "IxPlotCrop"           ON "Plot"("CropId");
CREATE INDEX "IxInsuranceInsurer"   ON "Insurance"("InsurerId");
CREATE INDEX "IxQuoteUser"          ON "InsuranceQuote"("UserId");
CREATE INDEX "IxQuotePlot"          ON "InsuranceQuote"("PlotId");
CREATE INDEX "IxPolicyPlot"         ON "Policy"("PlotId");
CREATE INDEX "IxPolicyInsurer"      ON "Policy"("InsurerId");
CREATE INDEX "IxClaimPolicy"        ON "Claim"("PolicyId");
CREATE INDEX "IxClaimSituation"     ON "Claim"("ClaimSituationId");
CREATE INDEX "IxClaimItemClaim"     ON "ClaimItem"("ClaimId");
CREATE INDEX "IxSatAnalysisPlot"    ON "SatelliteAnalysis"("PlotId", "ImageDate" DESC);
CREATE INDEX "IxSatAnalysisClaim"   ON "SatelliteAnalysis"("ClaimId");
CREATE INDEX "IxAlertPlot"          ON "PreventiveAlert"("PlotId", "IssuedAt" DESC);
CREATE INDEX "IxPaymentClaim"       ON "Payment"("ClaimId");
CREATE INDEX "IxPaymentPolicy"      ON "Payment"("PolicyId");
CREATE INDEX "IxPaymentInvoice"     ON "Payment"("PaymentInvoiceId");
CREATE INDEX "IxAuditLogUser"       ON "AuditLog"("UserId", "OperatedAt" DESC);
CREATE INDEX "IxAuditLogTarget"     ON "AuditLog"("TargetEntity", "TargetEntityId");
CREATE INDEX "IxAuditLogDescJson"   ON "AuditLog" USING GIN ("DescriptionJson");  -- busca dentro do JSONB

-- =============================================================================
-- FIM — 39 tabelas, ~55 FKs, 22 índices
-- Validação:
--   SELECT count(*) FROM information_schema.tables WHERE table_schema='public';
-- =============================================================================
